#!/bin/bash

set -x

echo "Installing Docker"

sudo apt-get remove docker docker-engine docker.io containerd runc -y
sudo apt-get update -y
sudo apt-get install -y \
    ca-certificates \
    curl \
    gnupg \
    lsb-release
rm -f /usr/share/keyrings/docker-archive-keyring.gpg
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
sudo apt-get update -y
sudo apt-get install -y docker-ce docker-ce-cli containerd.io git

sudo groupadd docker
sudo usermod -aG docker $USER

sudo systemctl enable docker.service
sudo systemctl enable containerd.service
sudo systemctl start docker.service
sudo systemctl start containerd.service


echo "Installing Docker-Compose"

sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
sudo chmod +x /usr/local/bin/docker-compose
sudo ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose
docker-compose --version




echo "Installing Poste"

git clone https://github.com/merchantprotocol/poste.git
cd poste

docker-compose up -d
echo "Waiting for Poste container to boot up..."
sleep 60

#docker exec mailserver poste domain:create example.com
#docker exec mailserver poste email:create admin@example.com
#docker exec mailserver poste email:passwd admin@example.com admin
#docker exec mailserver poste email:admin admin@example.com

IP=$(hostname  -I | cut -f1 -d' ')
echo "You can now access your Poste Install http://$IP/admin/install/server"

